/** Traduceri EN. Cheile sunt textele românești; identificatorii și URL-urile rămân stabile. */
export const english: Record<string, string> = {
  "Vezi studiul de caz: {name}": "View case study: {name}",
  "Studiu de caz": "Case study",
  "De la problema inițială la soluția realizată. Descoperiți povestea fiecărui proiect.": "From the initial problem to the delivered solution. Explore the story behind each project.",
  "Fiecare proiect are un studiu de caz și un link separat către site.": "Each project has a case study and a separate link to its website.",
  "Captură a site-ului {name}": "Screenshot of the {name} website",
  "Previzualizare proiect": "Project preview",
  "Proiectul pe scurt": "Project at a glance",
  "Tip de proiect": "Project type",
  "Disponibilitate": "Availability",
  "Proiect publicat": "Published project",
  "Rolul meu": "My role",
  "Deschide site-ul": "Visit website",
  "(filă nouă)": "(new tab)",
  "Toate proiectele": "All projects",
  "Contextul și problema": "Context and challenge",
  "Contribuția mea": "My contribution",
  "Soluția realizată": "The solution",
  "Rezultatul": "The outcome",
  "Transparență în planificare": "Transparent planning",
  "Scopul, costurile și etapele sunt scrise în propunere. Modificările sunt discutate înainte de implementare.": "The scope, costs and milestones are set out in the proposal. Changes are discussed before implementation.",
  "Control asupra proiectului": "Control over your project",
  "Codul sursă, accesele și documentația vă aparțin. Găzduirea se stabilește în funcție de cerințe.": "The source code, access credentials and documentation belong to you. Hosting is agreed according to your requirements.",
  "Decizii documentate": "Documented decisions",
  "Arhitectura, integrările și instrucțiunile de operare sunt explicate pentru cei care continuă proiectul.": "Architecture, integrations and operating instructions are explained for the people who continue the project.",
  "Continuitate după lansare": "Continuity after launch",
  "Mentenanța și intervențiile se pot stabili separat, cu priorități și responsabilități clare.": "Maintenance and support can be agreed separately, with clear priorities and responsibilities.",
  "Dan Enache, inginer software din Iași. Aplicații cloud, produse SaaS și colaborare directă, de la idee la lansare.": "Dan Enache, software engineer based in Iași. Cloud applications, SaaS products and direct collaboration, from idea to launch.",
  "Despre": "About",
  "Iași, România · colaborare remote": "Iași, Romania · working remotely",
  "Un partener tehnic implicat în fiecare etapă.": "A technical partner involved at every stage.",
  "Dan Enache este un studio independent de dezvoltare software. Colaborarea pornește de la nevoile afacerii și continuă cu implementare, livrare și suport tehnic.": "Dan Enache is an independent software development studio. Every collaboration starts with your business needs and continues through implementation, delivery and technical support.",
  "Coordonare și dezvoltare": "Planning and development",
  "Inginer software · dezvoltator independent": "Software engineer · independent developer",
  "Contactul direct pentru evaluarea, organizarea și livrarea proiectului dumneavoastră.": "Your direct contact for assessing, planning and delivering your project.",
  "Să discutăm": "Let's talk",
  "Despre activitate": "What we do",
  "Dezvoltare software conectată la realitatea afacerii.": "Software development grounded in your business.",
  "Construim aplicații cloud, produse SaaS și integrări pentru companii care vor să își organizeze mai bine operațiunile. Pornim de la fluxurile de lucru și definim împreună rezultatul așteptat.": "We build cloud applications, SaaS products and integrations for companies looking to organise their operations. We start with your workflows and define the expected outcome together.",
  "Dan Enache rămâne implicat de la prima discuție până la lansare. Dacă proiectul necesită un specialist extern, rolul și contribuția lui sunt discutate înainte.": "Dan Enache stays involved from the first conversation through to launch. If the project needs an external specialist, their role and contribution are agreed in advance.",
  "Analiză și propunere de implementare": "Analysis and implementation proposal",
  "Dezvoltare, testare și livrare în etape": "Development, testing and phased delivery",
  "Operare cloud, documentație și mentenanță": "Cloud operations, documentation and maintenance",
  "Colaborăm cu": "We work with",
  "Proiecte publicate în portofoliu": "Published projects in our portfolio",
  "Servicii de dezvoltare și operare": "Development and operations services",
  "Colaborare": "Collaboration",
  "Răspuns la solicitări": "Response to enquiries",
  "2 zile lucrătoare": "2 business days",
  "Principii de colaborare": "Working principles",
  "Responsabilități clare, de la început.": "Clear responsibilities from the start.",
  "O bază comună pentru deciziile tehnice și comerciale.": "A shared basis for technical and business decisions.",
  "Proces": "Process",
  "Cum decurge un proiect.": "How a project works.",
  "Etape vizibile și un punct de contact pe tot parcursul colaborării.": "Visible milestones and one point of contact throughout the collaboration.",
  "Datele operatorului": "Business details",
  "Confidențialitate": "Privacy",
  "Scrieți-ne despre procesul pe care vreți să îl automatizați sau despre aplicația de care aveți nevoie.": "Tell us about the process you want to automate or the application you need.",
  "Răspuns în maximum două zile lucrătoare": "Response within two business days",
  "Să discutăm despre proiectul dumneavoastră.": "Let's discuss your project.",
  "O aplicație nouă, o integrare sau un proiect existent. Trimiteți câteva detalii și stabilim împreună următorul pas.": "A new application, an integration or an existing project. Send us a few details and we will agree on the next step together.",
  "Contact direct": "Direct contact",
  "Dan Enache · Inginer software": "Dan Enache · Software engineer",
  "Locație": "Location",
  "Timp de răspuns": "Response time",
  "Maximum două zile lucrătoare": "Within two business days",
  "Ce ne ajută să știm": "What helps us understand your needs",
  "Ce doriți să construiți sau să simplificați": "What you want to build or simplify",
  "Cine va folosi soluția": "Who will use the solution",
  "Ce aplicații trebuie conectate": "Which applications need to connect",
  "Un termen sau un buget orientativ, dacă există": "An indicative deadline or budget, if available",
  "După trimitere": "After you submit",
  "Primiți o confirmare automată pe e-mail.": "You receive an automatic email confirmation.",
  "Analizăm contextul și revenim cu întrebări.": "We review the context and follow up with questions.",
  "Stabilim o discuție și pașii pentru propunere.": "We arrange a conversation and agree on the steps towards a proposal.",
  "Trimiteți o solicitare": "Send an enquiry",
  "Descrieți pe scurt obiectivul. Nu este necesară o specificație tehnică.": "Briefly describe your goal. No technical specification is required.",
  "Dezvoltare software pentru afaceri": "Software development for business",
  "Dan Enache: dezvoltare de aplicații web și SaaS, integrări, automatizări și operare cloud. Un partener tehnic de la analiză la mentenanță.": "Dan Enache: web and SaaS application development, integrations, automation and cloud operations. A technical partner from analysis to maintenance.",
  "Dan Enache · Dezvoltare software": "Dan Enache · Software development",
  "Software potrivit": "Software built for",
  "afacerii dumneavoastră.": "your business.",
  "Dezvoltăm aplicații web, conectăm sisteme și automatizăm procese. Un partener tehnic pentru tot parcursul proiectului, de la analiză la lansare și mentenanță.": "We develop web applications, connect systems and automate processes. A technical partner throughout your project, from analysis to launch and maintenance.",
  "Discutăm proiectul": "Discuss your project",
  "Proiecte realizate": "View our projects",
  "Soluții pentru": "Solutions for",
  "Servicii": "Services",
  "Expertiză organizată în jurul nevoilor afacerii.": "Expertise built around your business needs.",
  "Dezvoltare, conectare și operare. Fiecare arie are livrabile și un proces de lucru clar.": "Development, integration and operations. Each area has clear deliverables and an established way of working.",
  "Livrabile, tehnologii și răspunsuri la întrebări.": "Deliverables, technologies and answers to your questions.",
  "Toate serviciile": "All services",
  "Portofoliu": "Portfolio",
  "Proiecte publicate. Soluții concrete.": "Published projects. Practical solutions.",
  "Aplicații de business, site-uri de prezentare și publicații digitale. Fiecare card deschide proiectul.": "Business applications, company websites and digital publications. Each card opens the project.",
  "Descoperiți proiectele și demonstrațiile de capabilitate.": "Explore our projects and capability demos.",
  "Portofoliul complet": "Full portfolio",
  "Mod de lucru": "How we work",
  "Un proces previzibil, de la discuție la livrare.": "A predictable process, from discussion to delivery.",
  "Știți ce se construiește, ce primiți și care este următorul pas.": "You know what is being built, what you will receive and what comes next.",
  "Colaborare directă cu Dan Enache, inginer software.": "Work directly with Dan Enache, software engineer.",
  "Despre colaborare": "About working together",
  "Pagină inexistentă": "Page not found",
  "Adresa accesată nu corespunde niciunei pagini.": "This address does not match any page.",
  "Pagina nu a fost găsită": "Page not found",
  "Pagina aceasta nu există.": "This page does not exist.",
  "Verificați adresa sau continuați către una dintre secțiunile principale.": "Check the address or continue to one of the main sections.",
  "Înapoi acasă": "Back to home",
  "Servicii software": "Software services",
  "Proiecte publicate": "Published projects",
  "Contabo, PCS, Poetio și RVR Taxi: proiecte reale de aplicații web, site-uri de prezentare și publicații digitale, alături de demonstrații interne.": "Contabo, PCS, Poetio and RVR Taxi: real web applications, company websites and digital publications, alongside internal demos.",
  "Proiecte": "Projects",
  "Proiecte reale · demonstrații marcate distinct": "Real projects · clearly labelled demos",
  "Proiecte software și prezențe digitale.": "Software projects and digital experiences.",
  "Contabo, PCS, Poetio și RVR Taxi: de la contabilitate și operațiuni taxi la comunicare publică și poezie. Soluții construite pentru nevoi și utilizatori diferiți.": "Contabo, PCS, Poetio and RVR Taxi: from accounting and taxi operations to public communication and poetry. Solutions built for different needs and users.",
  "Filtrați proiectele": "Filter projects",
  "Filtrare după categorie": "Filter by category",
  "proiect publicat": "published project",
  "proiecte publicate": "published projects",
  "demonstrație": "demo",
  "demonstrații": "demos",
  "Fiecare card deschide site-ul într-o filă nouă.": "Each card opens the website in a new tab.",
  "Demonstrații de capabilitate": "Capability demos",
  "Studii interne care ilustrează tipuri de aplicații și integrări. Acestea nu sunt proiecte publicate și nu au un site de vizitat.": "Internal studies illustrating types of applications and integrations. These are not published projects and have no live website.",
  "Proiect real": "Live project",
  "Demonstrație": "Demo",
  "Problema.": "The problem.",
  "Abordarea.": "The approach.",
  "Rezultatul.": "The result.",
  "Vezi proiectul": "View project",
  "Ce date colectăm prin formularul de contact, ce facem cu ele și ce drepturi aveți.": "What data we collect through the contact form, how we use it and your rights.",
  "Ce date colectăm și cum le folosim.": "What data we collect and how we use it.",
  "Informații despre formularul de contact, conturile de client, păstrarea datelor și exercitarea drepturilor.": "Information about the contact form, client accounts, data retention and exercising your rights.",
  "Cuprins confidențialitate": "Privacy contents",
  "În această pagină": "On this page",
  "Întrebări despre date?": "Questions about your data?",
  "Notă.": "Note.",
  "Textul descrie funcționarea tehnică actuală a site-ului și datele operatorului; pentru utilizare juridică trebuie revizuit de un consultant.": "This text describes the current technical operation of the website and identifies the operator; it should be reviewed by an adviser before use as a legal document.",
  "Înapoi la formular": "Back to the form",
  "Aplicații cloud, integrări și automatizări, AI aplicat, mentenanță și operare pe infrastructură proprie.": "Cloud applications, integrations and automation, applied AI, maintenance and operations on our own infrastructure.",
  "Dezvoltare · Integrări · Operare": "Development · Integrations · Operations",
  "Servicii software, de la analiză la mentenanță.": "Software services, from analysis to maintenance.",
  "Cinci servicii, grupate în trei arii de expertiză. Consultați livrabilele și modul de lucru, apoi discutăm ce se potrivește proiectului dumneavoastră.": "Five services across three areas of expertise. Explore the deliverables and how we work, then let's discuss what fits your project.",
  "Servicii disponibile": "Available services",
  "Alegeți o arie": "Choose an area",
  "Un proiect existent?": "An existing project?",
  "Putem începe cu un audit și un plan de îmbunătățire.": "We can start with an audit and an improvement plan.",
  "Discutăm situația": "Discuss your needs",
  "Ce livrăm": "What we deliver",
  "Mod de lucru și tehnologii": "Approach and technologies",
  "Discutați acest serviciu": "Discuss this service",
  "Întrebări frecvente": "Frequently asked questions",
  "Detaliile unei colaborări.": "The details of working together.",
  "Buget, proprietatea codului și suport după lansare.": "Budget, code ownership and support after launch.",
  "Să discutăm despre proiect": "Let's discuss your project",
  "De la o nevoie concretă la o soluție software.": "From a business need to a software solution.",
  "Descrieți obiectivul. Revenim cu întrebările potrivite și următorii pași.": "Describe your goal. We will follow up with the right questions and next steps.",
  "Trimiterea a eșuat.": "Your message could not be sent.",
  "Formular în mod demonstrativ.": "Demo form.",
  "Nu este configurat niciun serviciu de trimitere, așa că mesajul nu pleacă nicăieri. Validarea funcționează, iar după completare primiți un link care deschide mesajul în clientul dumneavoastră de e-mail. Pentru trimitere reală, setați": "No delivery service is configured, so nothing is sent. Validation works, and after completing the form you will receive a link to open the message in your email application. To enable delivery, set",
  "Nume și prenume": "Full name",
  "E-mail": "Email",
  "Organizație": "Organisation",
  "(opțional)": "(optional)",
  "Subiect": "Subject",
  "Altceva": "Something else",
  "Despre ce este vorba": "Tell us about your project",
  "Ce proces vă consumă timp astăzi, cine îl folosește și ce sisteme sunt implicate. Detaliile ajută la un răspuns concret. Minimum 20 și maximum 5.000 de caractere.": "Which process takes up your time today, who uses it and which systems are involved? Details help us give you a useful response. Between 20 and 5,000 characters.",
  "caractere": "characters",
  "Nu completați acest câmp": "Leave this field empty",
  "Se trimite…": "Sending…",
  "Trimite mesajul": "Send message",
  "Răspundem în maximum două zile lucrătoare.": "We reply within two business days.",
  "Folosim datele doar pentru a răspunde solicitării. Detalii în": "We use your data only to respond to your enquiry. Details in our",
  "nota de confidențialitate": "privacy notice",
  "Mesaj trimis.": "Message sent.",
  "Vă răspundem pe adresa indicată.": "We will reply to the email address you provided.",
  "Datele sunt valide, dar mesajul nu a fost trimis": "Your details are valid, but the message has not been sent",
  "— formularul rulează în mod demonstrativ.": "— the form is running in demo mode.",
  "Deschideți mesajul în clientul de e-mail": "Open the message in your email application",
  "sau scrieți direct la": "or email us directly at",
  "Încercați din nou sau scrieți la": "Please try again or email",
  "Componentele unei soluții software": "The components of a software solution",
  "DEZVOLTARE CAP-COADĂ": "END-TO-END DEVELOPMENT",
  "CONSTRUIT ÎN JURUL AFACERII": "BUILT AROUND YOUR BUSINESS",
  "Soluția dumneavoastră": "Your solution",
  "O interfață clară. Procese conectate.": "A clear interface. Connected processes.",
  "Aplicație": "Application",
  "Web · SaaS · Portaluri": "Web · SaaS · Portals",
  "Integrări": "Integrations",
  "API · Date · Automatizări": "APIs · Data · Automation",
  "Infrastructură": "Infrastructure",
  "Cloud · Backup · Operare": "Cloud · Backup · Operations",
  "De la analiză la livrare": "From analysis to delivery",
  "Obiective și specificații": "Goals and specifications",
  "Dezvoltare și testare": "Development and testing",
  "Lansare și documentație": "Launch and documentation",
  "Același partener, în fiecare etapă.": "The same partner, at every stage.",
  "Dezvoltare software, integrări și operare cloud pentru afaceri.": "Software development, integrations and cloud operations for business.",
  "Companie": "Company",
  "Discutăm un proiect?": "Have a project in mind?",
  "Revenim în maximum două zile lucrătoare.": "We will get back to you within two business days.",
  "· Dezvoltare software": "· Software development",
  "Dan Enache — Software Developer — Acasă": "Dan Enache — Software Developer — Home",
  "Navigație principală": "Main navigation",
  "Explorați Dan Enache": "Explore Dan Enache",
  "Închide navigația": "Close navigation",
  "Cont": "Account",
  "Închide meniul": "Close menu",
  "Deschide meniul": "Open menu",
  "Limba site-ului": "Website language",
  "Sari la conținut": "Skip to content",
  "Locație în site": "Breadcrumb",
  "Acasă": "Home",
  "Vezi site-ul": "Visit website",
  "Comută pe tema deschisă": "Switch to light theme",
  "Comută pe tema întunecată": "Switch to dark theme",
  "Aplicații cloud și produse SaaS": "Cloud applications and SaaS products",
  "Sunt Dan Enache, inginer software din Iași. Transform idei și procese complicate în aplicații clare, utile și ușor de folosit.": "I'm Dan Enache, a software engineer from Iași. I turn ideas and complicated processes into clear, useful applications that are easy to use.",
  "Construiesc aplicații web, produse SaaS și integrări. Sunt contactul tău direct, de la prima idee până la lansare și mentenanță.": "I build web applications, SaaS products and integrations. I am your direct contact, from the first idea through to launch and maintenance.",
  "IMM-uri": "SMEs",
  "Startup-uri SaaS": "SaaS startups",
  "Echipe enterprise": "Enterprise teams",
  "Cont client": "Client account",
  "Aplicații cloud pe măsură": "Custom cloud applications",
  "Platforme interne, portaluri pentru clienți și aplicații care înlocuiesc fișierele Excel și procesele manuale.": "Internal platforms, client portals and applications that replace spreadsheets and manual processes.",
  "Pornim de la fluxul real de lucru, nu de la un template. Modelăm datele, definim rolurile și permisiunile, apoi construim interfața peste un API documentat. Livrăm în incremente funcționale, ca să folosiți aplicația înainte să fie „gata” complet.": "We start with your actual workflow. We model the data, define roles and permissions, then build the interface around a documented API. We deliver working increments so you can use the application before every feature is complete.",
  "Model de date și API documentat": "Data model and documented API",
  "Interfață responsivă, testată pe desktop și mobil": "Responsive interface tested on desktop and mobile",
  "Roluri, permisiuni și jurnal de audit": "Roles, permissions and audit log",
  "Pipeline de build și deploy automat": "Automated build and deployment pipeline",
  "Integrări și automatizări": "Integrations and automation",
  "Conectăm sistemele care nu vorbesc între ele: ERP, CRM, facturare, e-Factura, curieri, plăți.": "We connect systems that do not communicate: ERP, CRM, invoicing, e-Factura, couriers and payments.",
  "Majoritatea pierderilor de timp apar la granița dintre sisteme. Construim integrări cu reîncercări, jurnalizare și alertare, astfel încât o eroare de rețea să nu devină o comandă pierdută. Fiecare integrare vine cu un mod de testare separat de producție.": "Most wasted time occurs between systems. We build integrations with retries, logging and alerts so a network error does not become a lost order. Every integration includes a testing environment separate from production.",
  "Sincronizări programate sau pe eveniment (webhooks)": "Scheduled or event-driven synchronisation (webhooks)",
  "Reîncercări, cozi și tratarea erorilor": "Retries, queues and error handling",
  "Jurnal de rulări, vizibil pentru echipa dvs.": "Execution logs visible to your team",
  "Documentație de operare și rollback": "Operations and rollback documentation",
  "Cozi de mesaje": "Message queues",
  "Funcționalități cu AI, aplicate": "Practical AI features",
  "Asistență la clasificare, extragere de date din documente și căutare semantică — acolo unde reduc muncă reală.": "Support for classification, document data extraction and semantic search where they reduce actual work.",
  "Nu adăugăm AI ca argument de marketing. Începem cu o sarcină măsurabilă, stabilim un prag de acuratețe acceptat împreună cu dvs. și păstrăm întotdeauna un traseu de verificare umană. Dacă evaluarea nu trece pragul, spunem asta și oprim direcția.": "We start with a measurable task, agree on an accuracy threshold with you and keep a human review path available. If the evaluation does not meet that threshold, we explain the outcome and stop that approach.",
  "Set de evaluare pe datele dumneavoastră": "Evaluation dataset using your own data",
  "Prag de acuratețe agreat înainte de implementare": "Accuracy threshold agreed before implementation",
  "Interfață de verificare și corectare umană": "Human review and correction interface",
  "Estimare de cost per operațiune": "Cost estimate per operation",
  "API-uri LLM": "LLM APIs",
  "Căutare vectorială": "Vector search",
  "Evaluări automate": "Automated evaluations",
  "Preluare și mentenanță": "Project takeover and maintenance",
  "Preluăm proiecte existente, stabilizăm ce e fragil și documentăm ce a rămas nescris.": "We take over existing projects, stabilise fragile areas and document what was left unwritten.",
  "Începem cu un audit scurt: dependențe, riscuri de securitate, acoperire cu teste, procesul de release. Primiți un raport cu problemele ordonate după impact și cost, iar dumneavoastră decideți ce reparăm și în ce ordine.": "We start with a short audit of dependencies, security risks, test coverage and the release process. You receive a report ranking issues by impact and cost, then decide what we fix and in what order.",
  "Audit tehnic scris, cu priorități": "Written technical audit with priorities",
  "Actualizări de dependențe și securitate": "Dependency and security updates",
  "Teste pentru zonele critice": "Tests for critical areas",
  "Predare completă: acces, documentație, cod": "Full handover: access, documentation and code",
  "Teste": "Testing",
  "Monitorizare": "Monitoring",
  "Livrare și operare în cloud": "Cloud delivery and operations",
  "Publicăm și operăm aplicații pe infrastructură proprie, cu procese clare de actualizare, monitorizare și recuperare.": "We deploy and operate applications on our own infrastructure, with clear processes for updates, monitoring and recovery.",
  "Pregătim aplicația pentru producție, separăm mediile de test și producție și automatizăm livrările. Configurăm jurnalizarea, monitorizarea, copiile de siguranță și procedurile de restaurare, astfel încât operarea să nu depindă de intervenții improvizate.": "We prepare the application for production, separate testing and production environments and automate releases. We configure logging, monitoring, backups and recovery procedures so operations do not rely on improvised fixes.",
  "Mediu de test și mediu de producție separate": "Separate testing and production environments",
  "Deploy automat și procedură de revenire": "Automated deployment and rollback procedure",
  "Monitorizare, alerte și jurnalizare": "Monitoring, alerts and logging",
  "Backup verificat și documentație de restaurare": "Verified backups and recovery documentation",
  "Containere": "Containers",
  "Discuție și delimitare": "Discovery and scope",
  "Zilele 1–3": "Days 1–3",
  "O conversație despre problema concretă, nu despre tehnologie. Ieșim cu obiectivul, constrângerile, integrările necesare și ce înseamnă „funcționează” pentru dumneavoastră.": "A conversation about the actual problem. We define the goal, constraints, required integrations and what a working solution means for you.",
  "Propunere cu preț și plan": "Proposal, price and plan",
  "Săptămâna 1": "Week 1",
  "Primiți un document cu scopul lucrării, etapele, prețul și ce nu este inclus. Dacă bugetul nu acoperă tot, propunem o variantă redusă care rămâne utilă.": "You receive a document with the scope, milestones, price and exclusions. If the budget does not cover everything, we propose a smaller version that is still useful.",
  "Livrare în incremente": "Incremental delivery",
  "Continuu": "Ongoing",
  "Lucrăm în cicluri scurte, cu o versiune accesibilă în mediu de test. Vedeți progresul săptămânal și puteți schimba prioritățile între cicluri.": "We work in short cycles, with a version available in a testing environment. You see progress each week and can change priorities between cycles.",
  "Lansare și predare": "Launch and handover",
  "La final": "At completion",
  "Punem în producție, configurăm monitorizarea și predăm codul, accesele și documentația. Rămâneți proprietarul întregului cod sursă.": "We deploy to production, configure monitoring and hand over the code, access credentials and documentation. You retain ownership of all the source code.",
  "Contabo — contabilitate completă în cloud": "Contabo — complete cloud accounting",
  "Documente, e-Factura și rapoarte contabile într-o singură platformă online.": "Documents, e-Factura and accounting reports in one online platform.",
  "Documentele, facturarea, registrele și raportarea unei firme ajung ușor în aplicații și pași separați, greu de urmărit fără experiență contabilă.": "A company's documents, invoicing, ledgers and reporting often end up spread across separate applications and steps that are difficult to follow without accounting experience.",
  "O platformă online care grupează documentele primite și emise, e-Factura, banca și casa, balanța, TVA-ul, stocurile, salariile și rapoartele într-un flux ghidat.": "An online platform bringing incoming and outgoing documents, e-Factura, bank and cash accounts, trial balances, VAT, inventory, payroll and reports into a guided workflow.",
  "Produs SaaS funcțional, disponibil public, cu înscriere de firmă și moduri demo distincte pentru patron și contabil.": "A working SaaS product available to the public, with company registration and separate demo modes for business owners and accountants.",
  "PCS — Partidul Conservator al Seniorilor": "PCS — Conservative Party of Seniors",
  "Site-uri de prezentare": "Company websites",
  "Site de prezentare cu program, știri, documente și informații despre organizațiile PCS.": "A presentation website with the programme, news, documents and information about PCS organisations.",
  "Prezentarea unei organizații, a documentelor și a informațiilor publice are nevoie de o structură clară, ușor de parcurs.": "Presenting an organisation, its documents and public information requires a clear structure that is easy to navigate.",
  "Un site cu secțiuni pentru program, știri, documente și organizații teritoriale, alături de acces la contact și aderare.": "A website with sections for the programme, news, documents and regional organisations, as well as contact and membership information.",
  "Site public care reunește prezentarea PCS și informațiile despre activitatea organizației.": "A public website bringing together the PCS presentation and information about the organisation's activities.",
  "Prezentare": "Presentation",
  "Conținut public": "Public content",
  "Organizații": "Organisations",
  "Poetio — un spațiu pentru poezie": "Poetio — a space for poetry",
  "Publicații digitale": "Digital publications",
  "Poeziile lui Dan Enache într-un spațiu de lectură cu pagini dedicate poemelor și comentarii.": "Poems by Dan Enache in a reading space with individual poem pages and comments.",
  "O colecție de poezie are nevoie de un spațiu de lectură aerisit, care pune textul și autorul în prim-plan.": "A poetry collection needs an uncluttered reading space that places the text and author first.",
  "O publicație digitală cu pagini dedicate poemelor, comentarii, secțiuni pentru video, cărți și autor, plus opțiuni de limbă și temă vizuală.": "A digital publication with individual poem pages, comments, video, book and author sections, plus language and visual theme options.",
  "Colecție publică de poeme semnate de Dan Enache, cu navigare între texte și acces la pagina fiecărui poem.": "A public collection of poems by Dan Enache, with navigation between texts and a dedicated page for each poem.",
  "Poezie": "Poetry",
  "Design editorial": "Editorial design",
  "Publicație digitală": "Digital publication",
  "RVR Taxi — platformă pentru operațiuni taxi": "RVR Taxi — taxi operations platform",
  "Aplicații web": "Web applications",
  "Platformă pentru operațiuni taxi, cu organizații și conturi de utilizator. Acces după autentificare.": "A taxi operations platform with organisations and user accounts. Sign-in required.",
  "Accesul la o platformă de operațiuni taxi trebuie organizat în jurul conturilor de utilizator și al organizațiilor.": "Access to a taxi operations platform needs to be organised around user accounts and organisations.",
  "O aplicație web cu autentificare prin identificatorul organizației, e-mail și parolă, opțiune de creare a organizației și acces la un cont demonstrativ.": "A web application with sign-in using an organisation identifier, email and password, plus organisation registration and a demo account.",
  "Platformă disponibilă online, cu acces la funcționalități după autentificare.": "A platform available online, with features accessible after signing in.",
  "Operațiuni taxi": "Taxi operations",
  "Autentificare": "Authentication",
  "Panou de urmărire a comenzilor": "Order tracking dashboard",
  "Comenzile ajung din trei surse diferite, iar starea reală există doar într-un fișier partajat.": "Orders arrive from three different sources, while their actual status exists only in a shared file.",
  "Un singur ecran cu stările comenzii, istoric de modificări și filtre salvabile. Actualizările sunt împinse către interfață fără reîncărcarea paginii.": "One screen for order statuses, change history and saved filters. Updates reach the interface without reloading the page.",
  "Extragere de date din documente": "Document data extraction",
  "AI aplicat": "Applied AI",
  "Facturile primite pe e-mail sunt introduse manual în sistemul contabil.": "Invoices received by email are entered into the accounting system manually.",
  "Extragem câmpurile, marcăm nivelul de încredere și trimitem la verificare umană tot ce coboară sub pragul stabilit. Nimic nu intră automat fără confirmare.": "We extract fields, show confidence levels and send anything below the agreed threshold for human review. Nothing is entered automatically without confirmation.",
  "API LLM": "LLM API",
  "Cozi": "Queues",
  "Sincronizare de stoc între sisteme": "Inventory synchronisation between systems",
  "Stocul din magazinul online rămâne în urma stocului din depozit.": "Online store stock levels lag behind warehouse inventory.",
  "Sincronizare pe eveniment, cu reîncercări și cu un jurnal în care se vede exact ce a eșuat și de ce. Diferențele sunt raportate zilnic.": "Event-driven synchronisation with retries and a log showing exactly what failed and why. Discrepancies are reported daily.",
  "Portal pentru clienți": "Client portal",
  "Clienții sună pentru informații care ar putea fi disponibile permanent.": "Clients call for information that could be available at any time.",
  "Autentificare, documente, stadiul lucrărilor și facturi într-un singur loc, cu permisiuni pe organizație și jurnal de acces.": "Sign-in, documents, work status and invoices in one place, with organisation-based permissions and access logs.",
  "Raportare operațională": "Operational reporting",
  "Raportul de luni dimineață se face manual, din patru exporturi.": "The Monday morning report is compiled manually from four exports.",
  "Colectare automată în timpul nopții, verificări de consistență și un raport care semnalează explicit datele lipsă în loc să le ascundă.": "Automatic overnight collection, consistency checks and a report that explicitly flags missing data.",
  "Aplicație pentru echipe de teren": "Application for field teams",
  "Mobil": "Mobile",
  "Echipa completează formulare pe hârtie, iar datele ajung în sistem după câteva zile.": "The team fills in paper forms and the data reaches the system several days later.",
  "Aplicație care funcționează offline, cu sincronizare la revenirea semnalului și rezolvarea conflictelor pe ultima modificare confirmată.": "An offline-capable application that synchronises when connectivity returns and resolves conflicts using the last confirmed change.",
  "Sincronizare": "Synchronisation",
  "Toate": "All",
  "Estimări pe care le respectăm": "Estimates we stand by",
  "Dacă o estimare se dovedește greșită, aflați în aceeași săptămână, nu la termenul de livrare. Preferăm o discuție incomodă devreme unei surprize târzii.": "If an estimate proves wrong, you hear about it that week. We prefer an early conversation to a late surprise.",
  "Codul vă aparține": "You own the code",
  "Repository-ul, codul și documentația vă aparțin de la început. Găzduirea pe infrastructura noastră sau în mediul dumneavoastră este o alegere separată, explicită în propunere.": "The repository, code and documentation belong to you from the start. Hosting on our infrastructure or in your environment is a separate choice, made explicit in the proposal.",
  "Fără magie nedocumentată": "No undocumented decisions",
  "Fiecare decizie tehnică netrivială este scrisă undeva. Următorul dezvoltator care deschide proiectul trebuie să se descurce fără noi.": "Every significant technical decision is written down. The next developer who opens the project should be able to work without us.",
  "Refuzăm ce nu putem livra bine": "We are clear about our limits",
  "Dacă o cerință depășește ce putem susține la calitate, spunem asta și, când se poate, recomandăm pe altcineva.": "If a requirement goes beyond what we can deliver well, we say so and, where possible, recommend someone else.",
  "Cum se stabilește prețul?": "How is pricing agreed?",
  "Pentru lucrări cu scop clar propunem preț fix pe etape. Pentru dezvoltare continuă lucrăm cu tarif lunar și un plan revizuit la fiecare ciclu. Ambele variante sunt scrise în propunere înainte să înceapă lucrul.": "For clearly scoped work, we propose a fixed price per milestone. For ongoing development, we use a monthly fee and a plan reviewed each cycle. Both options are set out in the proposal before work starts.",
  "Lucrați cu proiecte începute de altcineva?": "Do you work on projects started by someone else?",
  "Da. Începem cu un audit tehnic plătit separat, la finalul căruia primiți raportul chiar dacă alegeți să nu continuați cu noi.": "Yes. We start with a separately priced technical audit. You receive the report even if you choose not to continue working with us.",
  "Cine deține codul și infrastructura?": "Who owns the code and infrastructure?",
  "Codul și documentația vă aparțin. Aplicația poate rula pe infrastructura noastră administrată sau în mediul dumneavoastră, în funcție de cerințele proiectului; alegerea și costurile sunt scrise în propunere.": "The code and documentation belong to you. The application can run on our managed infrastructure or in your environment, depending on the project's requirements. The choice and costs are set out in the proposal.",
  "Ce se întâmplă după lansare?": "What happens after launch?",
  "Puteți alege mentenanță lunară sau intervenție la cerere. În ambele cazuri, documentația de operare este livrată odată cu proiectul, ca să nu depindeți de un contract.": "You can choose monthly maintenance or support on request. In both cases, operating documentation is delivered with the project, so you are not dependent on a contract.",
  "Aplicații cloud": "Cloud applications",
  "Produse SaaS": "SaaS products",
  "Integrări API": "API integrations",
  "Automatizări": "Automation",
  "Mentenanță": "Maintenance",
  "24 septembrie 2026": "24 September 2026",
  "Cine prelucrează datele": "Who processes your data",
  "Operatorul este MOLDOVAN LUX S.R.L., cu sediul în Iași, CUI 30342978, înregistrată la Registrul Comerțului sub nr. J22/1026/21.06.2012.": "The controller is MOLDOVAN LUX S.R.L., based in Iași, tax identification number 30342978, registered with the Trade Register under no. J22/1026/21.06.2012.",
  "Pentru orice întrebare legată de datele dumneavoastră, ne puteți scrie la moldovanlux@gmail.com.": "For any questions about your data, you can contact us at moldovanlux@gmail.com.",
  "Ce date colectăm prin formular": "What data the form collects",
  "Formularul de contact solicită numele, adresa de e-mail, opțional organizația, subiectul ales și mesajul dumneavoastră. Nu cerem alte date și nu folosim câmpuri ascunse de profilare.": "The contact form asks for your name, email address, optional organisation, selected subject and message. We do not request other data or use hidden profiling fields.",
  "Există un singur câmp ascuns, o capcană anti-robot care trebuie să rămână goală. Conținutul lui nu este stocat și nu este transmis nicăieri.": "There is one hidden field: an anti-bot trap that must remain empty. Its contents are not stored or sent anywhere.",
  "Ce se întâmplă cu mesajul trimis": "What happens to your message",
  "Mesajul este transmis către serverul nostru și salvat într-o bază de date găzduită pe acel server. O notificare care include numele, adresa de e-mail, organizația și subiectul completate, precum și textul mesajului, este expediată prin serviciul Gmail al Google către moldovanlux@gmail.com, pentru a putea răspunde solicitării.": "Your message is sent to our server and saved in a database hosted on that server. A notification containing the name, email address, organisation, subject and message you entered is sent through Google's Gmail service to moldovanlux@gmail.com so we can respond to your enquiry.",
  "La adresa de e-mail completată în formular trimitem, tot prin Gmail, o confirmare automată de primire. Confirmarea nu include textul mesajului sau detaliile organizației.": "We also send an automatic receipt through Gmail to the email address entered in the form. The confirmation does not include the message text or organisation details.",
  "Accesul la mesajele salvate este restricționat: doar contul cu rol de administrator le poate vedea. Nu sunt publice și nu apar nicăieri pe site.": "Access to saved messages is restricted: only the administrator account can view them. They are not public and do not appear anywhere on the website.",
  "Nu reținem adresa dumneavoastră IP împreună cu mesajul. Adresele IP sunt folosite temporar, doar în memoria serverului, pentru a limita trimiterile repetate și a bloca roboții.": "We do not store your IP address alongside your message. IP addresses are used temporarily, only in server memory, to limit repeated submissions and block bots.",
  "Contul de client": "Your client account",
  "Crearea unui cont este opțională. Dacă vă faceți cont, stocăm numele, adresa de e-mail și parola în formă criptată ireversibil (scrypt). Nu putem citi parola și nu o putem recupera.": "Creating an account is optional. If you create one, we store your name, email address and an irreversible password hash (scrypt). We cannot read or recover your password.",
  "Adresa de e-mail a contului nu este verificată printr-un mesaj de confirmare; trimiterea prin Gmail este folosită pentru notificările formularului de contact. Din acest motiv, un cont nou nu vede cererile trimise anterior de la aceeași adresă: în cont apar doar cererile trimise cât timp sunteți autentificat. Este o măsură deliberată, ca nimeni să nu poată citi cererile altcuiva înregistrându-se cu adresa lui.": "Account email addresses are not verified through a confirmation message; Gmail delivery is used for contact form notifications. A new account therefore cannot see enquiries previously sent using the same address: it only shows enquiries submitted while signed in. This prevents someone from reading another person's enquiries by registering with their email address.",
  "Autentificarea folosește un cookie de sesiune strict necesar, valabil 30 de zile, pe care îl ștergeți ieșind din cont.": "Sign-in uses a strictly necessary session cookie valid for 30 days, which is deleted when you sign out.",
  "Temeiul și durata prelucrării": "Legal basis and retention",
  "Prelucrăm mesajul pentru a vă răspunde și, dacă se ajunge acolo, pentru a pregăti o ofertă. Temeiul este interesul legitim de a răspunde unei solicitări comerciale primite de la dumneavoastră, respectiv demersurile precontractuale.": "We process your message to respond and, where appropriate, prepare a proposal. The basis is our legitimate interest in responding to a business enquiry from you, or taking pre-contractual steps.",
  "Păstrăm mesajul atât timp cât este necesar discuției și obligațiilor legale ulterioare. Ne puteți cere oricând ștergerea; putem șterge o înregistrare individual, iar dacă nu există o obligație legală de păstrare, o facem.": "We keep the message for as long as needed for our discussion and subsequent legal obligations. You can request deletion at any time. Individual records can be deleted, and we will do so where there is no legal retention obligation.",
  "Cookie-uri, analiză și servicii externe": "Cookies, analytics and external services",
  "Site-ul public nu folosește cookie-uri, nu are instrumente de analiză a traficului și nu încarcă fonturi, hărți sau scripturi de la terți. Nicio pagină nu face cereri către alte domenii. Zona de administrare, accesibilă doar nouă, folosește un cookie de sesiune strict necesar pentru autentificare.": "The public website uses no cookies or traffic analytics and loads no third-party fonts, maps or scripts. No page makes requests to other domains. The administration area, accessible only to us, uses a strictly necessary session cookie for authentication.",
  "Serverul care găzduiește site-ul înregistrează, ca orice server web, adresa IP și pagina accesată, în jurnale tehnice folosite pentru funcționare și securitate.": "Like any web server, the server hosting this website records IP addresses and accessed pages in technical logs used for operation and security.",
  "Drepturile dumneavoastră": "Your rights",
  "Aveți dreptul de acces, rectificare, ștergere, restricționare, opoziție și portabilitate, conform Regulamentului (UE) 2016/679. Ne puteți contacta pe adresa din pagina de contact pentru oricare dintre ele.": "You have the rights of access, rectification, erasure, restriction, objection and portability under Regulation (EU) 2016/679. You can contact us using the email address on the contact page to exercise any of these rights.",
  "Dacă răspunsul nostru nu vă mulțumește, aveți dreptul să depuneți o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal.": "If you are not satisfied with our response, you have the right to lodge a complaint with Romania's National Supervisory Authority for Personal Data Processing.",
  "Dezvoltare de produse": "Product development",
  "Aplicații web, portaluri și produse SaaS construite în jurul proceselor afacerii.": "Web applications, portals and SaaS products built around your business processes.",
  "De la idee la aplicație": "From idea to application",
  "Integrări și automatizare": "Integrations and automation",
  "Sisteme conectate, mai puține operațiuni manuale și AI aplicat unde aduce valoare.": "Connected systems, fewer manual tasks and AI applied where it adds value.",
  "Procese care lucrează împreună": "Processes working together",
  "Cloud și mentenanță": "Cloud and maintenance",
  "Lansare, monitorizare și îmbunătățiri continue pentru aplicații noi sau existente.": "Launch, monitoring and ongoing improvements for new or existing applications.",
  "Clarificăm obiectivul, utilizatorii și sistemele implicate.": "We clarify the goal, users and systems involved.",
  "Stabilim livrabilele, etapele, bugetul și criteriile de acceptare.": "We agree on deliverables, milestones, budget and acceptance criteria.",
  "Vedeți progresul în versiuni funcționale și oferiți feedback.": "You see progress through working versions and provide feedback.",
  "Lansăm aplicația și predăm codul, accesul și documentația.": "We launch the application and hand over the code, access and documentation.",
  "Un contact direct": "One direct contact",
  "Discuțiile tehnice și deciziile rămân la aceeași persoană.": "Technical discussions and decisions stay with the same person.",
  "Livrabile clare": "Clear deliverables",
  "Scopul, etapele și costurile sunt stabilite înainte de dezvoltare.": "Scope, milestones and costs are agreed before development starts.",
  "Primiți codul sursă, documentația și accesul la proiect.": "You receive the source code, documentation and project access.",
  "Mesajul poate avea cel mult 5.000 de caractere.": "The message can contain up to 5,000 characters.",
  "Introduceți numele dumneavoastră.": "Please enter your name.",
  "Introduceți o adresă de e-mail validă.": "Please enter a valid email address.",
  "Descrieți pe scurt contextul — cel puțin 20 de caractere.": "Briefly describe your needs — at least 20 characters.",
  "contabilitate completă în cloud": "complete cloud accounting",
  "Partidul Conservator al Seniorilor": "Conservative Party of Seniors",
  "un spațiu pentru poezie": "a space for poetry",
  "platformă pentru operațiuni taxi": "taxi operations platform",
  "Preferințele pentru temă și limbă sunt salvate local în browser, în localStorage, sub cheile dan-enache-theme și dan-enache-language. Nu ne sunt transmise și dispar când ștergeți datele site-ului.": "Your theme and language preferences are saved locally in your browser using localStorage, under dan-enache-theme and dan-enache-language. These preferences are not sent to us and are removed when you clear the website's data.",
  "Actualizat {date}": "Updated {date}",
  "Deschide {name} — {domain} (filă nouă)": "Open {name} — {domain} (new tab)",
  "Trimiterea a eșuat ({error}).": "Your message could not be sent ({error}).",
  "Nume": "Name",
  "Cerere": "Enquiry",
  "Câmpurile trebuie să conțină text.": "Fields must contain text.",
  "Date invalide.": "Invalid details."
}
